name: Publish
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: gradle/wrapper-validation-action@v1

      # Generate the build number based on tags to allow per branch build numbers, not something github provides by default.
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ./gradlew applyPatches
      - run: ./gradlew build publish -x check -x test --stacktrace
        working-directory: ornithe-loom
        env:
          MAVEN_URL: ${{ secrets.NEW_MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.NEW_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEW_MAVEN_PASSWORD }}
